
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.15.0
 * Query Engine version: 85179d7826409ee107a6ba334b5e305ae3fba9fb
 */
Prisma.prismaVersion = {
  client: "6.15.0",
  engine: "85179d7826409ee107a6ba334b5e305ae3fba9fb"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  Article: 'Article',
  Description: 'Description',
  UPC: 'UPC',
  MerchID: 'MerchID',
  StyleID: 'StyleID',
  Style_Desc: 'Style_Desc',
  RootStyle: 'RootStyle',
  Brand: 'Brand',
  Sector: 'Sector',
  Category: 'Category',
  SubBrand: 'SubBrand',
  MP_A_SubBrand: 'MP_A_SubBrand',
  Collection: 'Collection',
  Class: 'Class',
  SubClass: 'SubClass',
  MasterStyleID: 'MasterStyleID',
  MasterStyle_Desc: 'MasterStyle_Desc',
  Choice_Code: 'Choice_Code',
  Choice_Desc: 'Choice_Desc',
  Color: 'Color',
  EC_Color: 'EC_Color',
  U_ChoiceDesc: 'U_ChoiceDesc',
  U_Form: 'U_Form',
  Size: 'Size',
  Size_1: 'Size_1',
  Size_2: 'Size_2',
  Material: 'Material',
  Case: 'Case',
  Lifecycle: 'Lifecycle',
  KeyItem: 'KeyItem',
  GS_Contents: 'GS_Contents',
  FST_GLB: 'FST_GLB',
  FST_CN: 'FST_CN',
  FST_HK: 'FST_HK',
  FST_Alt: 'FST_Alt',
  Set_CN: 'Set_CN',
  Set_GLB: 'Set_GLB',
  Set_HK: 'Set_HK',
  Push_CN: 'Push_CN',
  Push_HK: 'Push_HK',
  MKD_GLB: 'MKD_GLB',
  MKD_CN: 'MKD_CN',
  MKD_HK: 'MKD_HK',
  SAS_GLB: 'SAS_GLB',
  SAS_CN: 'SAS_CN',
  SAS_HK: 'SAS_HK',
  CNTier_LM: 'CNTier_LM',
  CNTier_TR: 'CNTier_TR',
  CNTier_FA: 'CNTier_FA',
  CNTier_OT: 'CNTier_OT',
  CNTier_EC: 'CNTier_EC',
  HKTier_BA: 'HKTier_BA',
  HKTier_FA: 'HKTier_FA',
  UPAS_Global: 'UPAS_Global',
  UPAS_CNBuy: 'UPAS_CNBuy',
  UPAS_HKBuy: 'UPAS_HKBuy',
  UPAS_CN: 'UPAS_CN',
  UPAS_HK: 'UPAS_HK',
  UPAS_CNFA: 'UPAS_CNFA',
  UPAS_CNBA: 'UPAS_CNBA',
  UPAS_CNEC: 'UPAS_CNEC',
  UPAS_HKFA: 'UPAS_HKFA',
  UPAS_HKBA: 'UPAS_HKBA',
  BuyPath: 'BuyPath',
  US_MSRP: 'US_MSRP',
  CN_MSRP: 'CN_MSRP',
  CN_Ticket: 'CN_Ticket',
  CN_StoreCost: 'CN_StoreCost',
  HK_MSRP: 'HK_MSRP',
  HK_Ticket: 'HK_Ticket',
  HK_StoreCost: 'HK_StoreCost',
  FA_Bundle: 'FA_Bundle',
  BA_Bundle: 'BA_Bundle',
  RegStatus: 'RegStatus',
  Unblocked: 'Unblocked',
  PDP: 'PDP',
  Comment: 'Comment',
  DmdUnit: 'DmdUnit',
  Matchback_CN: 'Matchback_CN',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Product: 'Product'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
